apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <cert_authority_key>
    server: <K3s_SERVER_IP>:6443
  name: default
contexts:
- context:
    cluster: default
    namespace: default
    user: depot-deployer
  name: default
current-context: default
kind: Config
users:
- name: depot-deployer
  user:
    token: <depot_deployer_token>
