apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: depot-oidc-token-request
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["depot-deployer"]
    verbs: ["create"]
