services:
  blog:
    volumes:
      - django_logs:/logs
    build:
      context: .
    expose:
      - 8000
    ports:
      - "${RDS_PORT}:${RDS_PORT}"
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      RDS_DB_NAME: ${RDS_DB_NAME}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - nginx_logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - blog
    restart: always

volumes:
  django_logs:
  nginx_logs:
