apiVersion: v1
kind: Pod
metadata:
  name: pg-restore
spec:
  restartPolicy: Never
  containers:
  - name: pg-client
    image: postgres:17
    command: ["/bin/bash","-c","sleep 3600"]
    env:
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_PASSWORD
      - name: PG_PORT
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_PORT
      - name: PG_USER
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_USER
      - name: PG_DATABASE
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_DATABASE
