apiVersion: v1
kind: Pod
metadata:
  name: helper-pod
spec:
  restartPolicy: Never
  containers:
  - name: helper-pod
    image: postgres:17
    command: ["/bin/bash","-c","sleep 3600"]
    env:
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_PASSWORD
      - name: PGPORT
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_PORT
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_USER
      - name: PGDATABASE
        valueFrom:
          secretKeyRef:
            name: pg-credentials
            key: PG_DATABASE
