# Generated by Django 5.2.1 on 2025-05-14 03:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
