# Generated by Django 5.2.1 on 2025-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="intro",
            field=models.CharField(default="", max_length=200),
        ),
    ]
