name: Test-Build-Plan-Deploy
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-python: true
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: uv run pytest
  build-container:
    needs: run-test
    runs-on: ubuntu-latest
    permissions:
      # required for allowing the workflow to request and use an OIDC token for an action or step
      # specifically, we need the below set for aws-actions/configure-aws-credentials@v4
      id-token: write
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v6
      - uses: depot/setup-action@v1

      - name: Build and Push with Depot
        uses: depot/build-push-action@v1
        with:
          context: .
          save: true
          save-tags: |
            latest
            ${{ github.sha }}
