name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          DJANGO_LOGLEVEL: ${{ secrets.DJANGO_LOGLEVEL }}
          RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
          RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_PORT: ${{ secrets.RDS_PORT }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add AWS_ACCOUNT_ID="$AWS_ACCOUNT_ID" DATABASE_ENGINE="$DATABASE_ENGINE" DJANGO_ALLOWED_HOSTS="$DJANGO_ALLOWED_HOSTS" DJANGO_LOGLEVEL="$DJANGO_LOGLEVEL" RDS_DB_NAME="$RDS_DB_NAME" RDS_HOSTNAME="$RDS_HOSTNAME" RDS_PASSWORD="$RDS_PASSWORD" RDS_PORT="$RDS_PORT" RDS_USERNAME="$RDS_USERNAME" SECRET_KEY="$SECRET_KEY" --repo Akatama/website
